import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css"
import "../styles/themify.css"
import Header from "@/components/header/header";

const geistSans = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PontoCarro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.className} light`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
