import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css"
import "../styles/themify.css"
import Header from "@/components/header/header";
import { AuthProvider } from '@/context/AuthContext';

const geistSans = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: ".Carro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.className} light`}>
        <AuthProvider>
          <Header />
          <main>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
